### ISSUE TITLE
[v1.00] Печать и сборка прототипа корпуса

### ISSUE THREAD

**Issue by NeoProg2013** [NeoProg2013/AIWM_hexapod#2]
Задача по печати корпуса. Это сообщение будет периодически обновляться в время печати и показывать прогресс и время печати каждой детали.

| Part name 	| Print time (x1) 	|  Progress 	|  % 		|  Status		|  Weight (g)	|
| ---- 		|:----:			|:----:		|:----:	|  :----:		|  :----:		|
| Base_1_1	| 4:00 			| 1\1  		| 100% 	|  Done		| ? 			|
| Base_1_2	| 4:10 			| 1\1  		| 100% 	|  Done		| ? 			|
| Base_1_3	| 8:40 			| 1\1  		| 100% 	|  Done		| ? 			|
| Base_1_4	| 2:20 			| 2\2  		| 100% 	|  Done		| ? 			|
| Base_1_5	| 3:20 			| 1\1  		| 100% 	|  Done		| ? 			|
| Top_cap		| 2:20 			| 1\1  		| 100% 	|  Done		| ? 			|
| Bot_cap		| 2:30 			| 1\1  		| 100% 	|  Done		| ? 			|
| Batt_cap	| 0:20 			| 1\1  		| 100% 	|  Done		| ? 			|
| Limb_1_1	| 1:40 			| 6\6  		| 100%	|  Done		| 36	 		|
| Limb_1_2	| 0:30 			| 6\6  		| 100% 	|  Done		| 5 			|
| Limb_1_3	| 0:30 			| 6\6  		| 100% 	|  Done		| 4 			|
| Limb_2_1	| 2:55 			| 6\6  		| 100% 	|  Done		| 53 			|
| Limb_2_2	| 1:00 			| 6\6  		| 100%	|  Done		| 12 			|
| Limb_3_1	| 2:33 			| 6\6  		| 100% 	|  Done		| 45 			|
| Limb_3_2	| 2:33 			| 3\3  		| 100% 	|  Done		| 30			|
| Limb_3_2_M	| 2:33 			| 3\3  		| 100%	|  Done		| 30 			|

M - деталь отражена зеркально

Вес центральной части (без приводов): 460g
Суммарный вес конечностей (без приводов): 1110g
Суммарный вес приводов: 1230g
Суммарный вес корпуса: 460 + 1110 + 1230 = 2800g

**Comment by NeoProgAIM** [comment]
Parts Base_1_1, Base_1_3 and Base_1_4 printing is completed after fix founded bugs:
1. Absent clearance between Base_1_1 and Base_1_3. Vertical slider is stuck.
2. Absent clearance between Base _1_1 and bottom part of Base_1_3. Vertical connectors on Base_1_3 is protrude.

**Comment by NeoProgAIM** [comment]
Сборка корпуса закончена. Больше косяков не обнаружено
